### ISSUE TITLE
TypeScript: Deceleration or Migrate

### ISSUE THREAD

**Issue by TheSeg** [markedjs/marked-xhtml#37]
**What pain point are you perceiving?.**
Even when including `@types/marked`, including `marked-xhtml` doesn't support TypeScript.

**Describe the solution you'd like**
[As Marked migrates to TypeScript](https://github.com/markedjs/marked/pull/2805), so should these new Marked support libraries. As they are small projects and the main project will remove the `@types/marked` dependency, I would request the migration route to reduce the need to add two packages per package.

**Comment by baseplate-admin** [comment]
@UziTech this can be closed i presume?

**Comment by UziTech** [comment]
Yes, thank you!
